import './globals.css'
import { Inter } from 'next/font/google'
import { Providers } from '@/globalRedux/provider'

const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app'
}

export default function RootLayout ({
  children
}: {
  children: React.ReactNode
}) {
  return (
    <html lang='en'>
      <body className={inter.className}>
        <main className='min-h-screen   xs:flex-col md:bg-white  md:flex'>
          <Providers>{children}</Providers>
        </main>
      </body>
    </html>
  )
}
